package io.dbax.conf;

import java.util.HashMap;

public final class ApexDynamicParameters {

	// Oracle Apex procedures for especial Parameter mapping
		public static final HashMap<String, HashMap<String, String>> apexProcedures = new HashMap<String, HashMap<String, String>>();
		//Especial procedures
		private static final HashMap<String, String> wwvFlowAccept = new HashMap<String, String>();
		private static final HashMap<String, String> wwvFlowShow = new HashMap<String, String>();
		private static final HashMap<String, String> wwvFlowClearPageCaches = new HashMap<String, String>();
		private static final HashMap<String, String> wwvFlowNullPageCaches = new HashMap<String, String>();
		private static final HashMap<String, String> wwvFlowNullStepCaches = new HashMap<String, String>();
		private static final HashMap<String, String> wwvFlowAjax = new HashMap<String, String>();
		

		static {
			// ParamName - Type
			wwvFlowAccept.put("p_arg_names", "wwv_flow_global.vc_arr2");			
			wwvFlowAccept.put("p_arg_values", "wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_json", "wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_files", "wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_arg_checksums", "wwv_flow_global.vc_arr2");			
			wwvFlowAccept.put("p_accept_processing", "wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_listener", "wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_map1", "wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_map2", "wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_map3", "wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v01","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v02","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v03","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v04","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v05","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v06","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v07","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v08","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v09","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v10","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v11","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v12","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v13","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v14","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v15","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v16","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v17","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v18","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v19","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v20","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v21","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v22","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v23","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v24","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v25","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v26","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v27","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v28","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v29","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v30","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v31","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v32","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v33","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v34","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v35","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v36","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v37","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v38","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v39","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v40","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v41","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v42","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v43","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v44","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v45","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v46","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v47","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v48","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v49","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v50","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v51","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v52","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v53","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v54","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v55","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v56","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v57","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v58","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v59","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v60","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v61","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v62","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v63","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v64","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v65","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v66","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v67","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v68","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v69","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v70","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v71","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v72","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v73","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v74","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v75","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v76","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v77","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v78","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v79","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v80","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v81","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v82","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v83","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v84","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v85","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v86","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v87","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v88","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v89","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v90","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v91","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v92","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v93","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v94","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v95","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v96","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v97","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v98","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v99","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v100","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v101","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v102","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v103","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v104","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v105","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v106","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v107","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v108","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v109","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v110","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v111","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v112","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v113","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v114","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v115","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v116","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v117","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v118","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v119","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v120","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v121","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v122","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v123","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v124","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v125","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v126","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v127","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v128","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v129","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v130","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v131","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v132","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v133","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v134","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v135","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v136","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v137","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v138","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v139","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v140","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v141","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v142","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v143","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v144","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v145","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v146","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v147","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v148","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v149","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v150","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v151","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v152","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v153","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v154","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v155","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v156","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v157","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v158","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v159","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v160","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v161","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v162","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v163","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v164","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v165","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v166","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v167","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v168","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v169","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v170","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v171","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v172","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v173","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v174","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v175","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v176","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v177","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v178","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v179","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v180","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v181","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v182","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v183","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v184","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v185","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v186","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v187","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v188","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v189","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v190","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v191","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v192","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v193","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v194","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v195","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v196","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v197","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v198","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v199","wwv_flow_global.vc_arr2");
			wwvFlowAccept.put("p_v200","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f01","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f02","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f03","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f04","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f05","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f06","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f07","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f08","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f09","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f10","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f11","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f12","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f13","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f14","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f15","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f16","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f17","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f18","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f19","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f20","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f21","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f22","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f23","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f24","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f25","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f26","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f27","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f28","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f29","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f30","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f31","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f32","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f33","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f34","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f35","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f36","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f37","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f38","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f39","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f40","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f41","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f42","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f43","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f44","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f45","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f46","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f47","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f48","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f49","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("f50","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("fcs","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("fmap","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("fhdr","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("fcud","wwv_flow_global.vc_arr2");
		    wwvFlowAccept.put("frowid","wwv_flow_global.vc_arr2");
			apexProcedures.put("wwv_flow.accept", wwvFlowAccept);

			wwvFlowShow.put("p_arg_names", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("p_arg_values", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("p_clear_cache", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f01", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f02", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f03", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f04", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f05", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f06", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f07", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f08", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f09", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f10", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f11", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f12", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f13", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f14", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f15", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f16", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f17", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f18", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f19", "wwv_flow_global.vc_arr2");
			wwvFlowShow.put("f20", "wwv_flow_global.vc_arr2");
			apexProcedures.put("wwv_flow.show", wwvFlowShow);
			
			wwvFlowClearPageCaches.put("p_flow_page_id", "wwv_flow_global.vc_arr2");
			apexProcedures.put("wwv_flow.clear_page_caches", wwvFlowClearPageCaches);
			
			wwvFlowNullPageCaches.put("p_flow_page_id", "wwv_flow_global.vc_arr2");
			apexProcedures.put("wwv_flow.null_page_caches", wwvFlowNullPageCaches);
			
			wwvFlowNullStepCaches.put("p_flow_page_id", "wwv_flow_global.vc_arr2");
			apexProcedures.put("wwv_flow.null_step_caches", wwvFlowNullStepCaches);
			
			wwvFlowAjax.put("p_arg_names", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("p_arg_values", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("p_json", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f01", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f02", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f03", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f04", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f05", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f06", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f07", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f08", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f09", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f10", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f11", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f12", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f13", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f14", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f15", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f16", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f17", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f18", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f19", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("f20", "wwv_flow_global.vc_arr2");
			wwvFlowAjax.put("p_clear_cache", "wwv_flow_global.vc_arr2");
			apexProcedures.put("wwv_flow.ajax", wwvFlowAjax);
			
		}
	
}
